server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/devtalk_prod_db?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=UTF-8
    username: ${db.username}  # /devtalk/prod/db/username
    password: ${db.password}  # /devtalk/prod/db/password

  # spring-boot-mail
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: dev.hongik@gmail.com # sender
    password: ${mail.smtpPassword}  # /devtalk/prod/mail/smtpPassword
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update  # 운영에서는 보통 none 또는 validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    open-in-view: false  # 운영에서는 비활성화 권장

  # AWS S3 Configuration
  cloud:
    aws:
      region:
        static: ap-northeast-2  # Seoul region
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    import: "aws-parameterstore:/devtalk/prod/"
    cloud:
      aws:
        region:
          static: ap-northeast-2
        parameterstore:
          enabled: true
          failFast: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: OFF

jwt:
  token:
    secretKey: ${jwt.secret} # /devtalk/prod/jwt/secret
    expiration:
      access: 14400000

aws:
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
    cloudfront-domain: ${AWS_CLOUDFRONT_DOMAIN:}  # Optional CloudFront domain

mail:
  from:
    address: dev.hongik@gmail.com
  templates:
    confirmation: https://hongik-devtalk-images.s3.ap-northeast-2.amazonaws.com/templates/confirmation/email_seminar_confirm.html
    reminder:
      offline: https://hongik-devtalk-images.s3.ap-northeast-2.amazonaws.com/templates/reminder/email_seminar_d-1_offline.html
      online: https://hongik-devtalk-images.s3.ap-northeast-2.amazonaws.com/templates/reminder/email_seminar_d-1_online.html
